[General]
BinaryDirectory = "C:/Program Files/Hamamatsu/Hiasphere/bin"
SubManagersLibraryName = [ "HiasSysManager.dll", "HiasSsdManager.dll" ]

[InterfaceManager]
LibraryName = "HiasInterfaceManager.dll"
Gige1 = "gige1"
Gige2 = "gige2"
Socket = "socket"
Usb = "usb"
# Dummy = "dummy"

[Log]
Enable = false
Filter = 0xFFBF
Directory = "C:/ProgramData/Hamamatsu/Hiasphere/log"
IncludeDateTimeInName = false
